#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

RED='\033[0;31m'
LIGHTPURPLE='\033[1;35m'
NOCOLOR='\e[0m'

if ! npx --no-install lint-staged; then
  # If the command fails, print an error message and exit with code 1
  echo "${RED}ERROR: Something got wrong, perhaps your changes failed a test! Check with ${LIGHTPURPLE}npm run test${RED} before commiting again${NOCOLOR}"
  exit 1
else
  # If the command succeeds, exit with code 0
  exit 0
fi
