name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Typechecking
        run: npm run typecheck

      - name: Test
        run: npm run test:coverage

      - name: Storybook
        run: npm run build-storybook
